services:
  springapp:
    image: pkumard4/springboot:latest
    depends_on:
    - mongo
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    networks:
    - javawebappoverlay
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
  mongo:
    image: mongo
    volumes:
    - mongovol:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    networks:
    - javawebappoverlay
volumes:
  mongovol:
    driver: local
networks:
  javawebappoverlay:
